#!/bin/bash
# Endpoints as found on http://docs.aws.amazon.com/general/latest/gr/rande.html on 2014-07-02

. $(dirname $0)/../helpers.sh
save_iptables drop_dynamodb_traffic

drop_traffic_to \
    dynamodb.us-east-1.amazonaws.com \
    dynamodb.us-west-2.amazonaws.com \
    dynamodb.us-west-1.amazonaws.com \
    dynamodb.eu-west-1.amazonaws.com \
    dynamodb.ap-southeast-1.amazonaws.com \
    dynamodb.ap-southeast-2.amazonaws.com \
    dynamodb.ap-northeast-1.amazonaws.com \
    dynamodb.sa-east-1.amazonaws.com

