#!/bin/bash
# TODO once start scripts are parameterizable make ports an input to this scripg

source $(dirname $0)/common

corruption=${1:-5%}

for IFACE in $IFACES; do
    $(dirname $0)/../network_condition/start $IFACE "80 443 3306 11211" "corrupt $corruption"
done
