#!/bin/bash -x

source $(dirname $0)/common

corruption=${1:-5%}

if shift && [ $# -ne 0 ]; then
    ports="$*"
else
    ports="80 443 3306 1211"
fi

for IFACE in $IFACES; do
    $(dirname $0)/../network_condition/start $IFACE "$ports" "corrupt $corruption"
done
