#!/bin/bash

. $(dirname $0)/../helpers.sh
save_iptables nullroute

client=${SSH_CLIENT%% *}

iptables -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -p tcp --source $client -j ACCEPT
iptables -A INPUT -j DROP

iptables -A OUTPUT -p tcp --sport 22 -j ACCEPT
iptables -A OUTPUT -p tcp --destination $client -j ACCEPT
iptables -A OUTPUT -j DROP