#!/bin/bash

IFACE=$1; shift
deplare -a MATCHES
while [ $# -gt 0 -a $1 != '--' ]; do
    MATCHES=("${MATCHES[@]}" "$1")
    shift
done
shift  # to get rid of '--'
CONDITION="$*"

tc qdisc add dev ${IFACE} root handle 1: prio bands 4 priomap 1 2 2 2 1 2 0 0 1 1 1 1 1 1 1 1
tc qdisc add dev ${IFACE} parent 1:4 handle 42: netem ${CONDITION}

for match in "${MATCHES[@]}"; do
    tc filter add dev ${IFACE} protocol ip parent 1: prio 1 u32 $match flowid 1:4
done

tc filter add dev ${IFACE} protocol ip parent 1: prio 1 u32 \
    match ip dport 22 0xffff \
    match ip sport 22 0xffff \
    flowid 1:1
