package com.prezi.fail.api.db

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.prezi.fail.api.Charge
import com.prezi.fail.api.ChargeStatus


// If anyone has infinite time, this could be generated.

[DynamoDBTable(tableName = "fail_Charge")]
class DBCharge([DynamoDBIgnore] val model: Charge = Charge()) {
    [DynamoDBAutoGeneratedKey]
    [DynamoDBHashKey(attributeName = "Id")]
    public var id: String? = null

    [DynamoDBAttribute(attributeName = "At")]
    public fun getAt(): Long? = model.getAt()
    public fun setAt(v: Long?): DBCharge? { model.setAt(v); return this }

    [DynamoDBAttribute(attributeName = "Status")]
    [DynamoDBMarshalling(marshallerClass = javaClass<EnumMarshaller>())]
    public fun getStatus(): ChargeStatus? = model.getStatus()
    public fun setStatus(v: ChargeStatus?): DBCharge? { model.setStatus(v); return this }

    [DynamoDBAttribute(attributeName = "Log")]
    public fun getLog(): String? = model.getLog()
    public fun setLog(v: String?): DBCharge? { model.setLog(v); return this }

    protected var _scheduledFailureId: String? = null

    [DynamoDBAttribute(attributeName = "ScheduledFailureId")]
    public fun getScheduledFailureId(): String? = _scheduledFailureId
    public fun setScheduledFailureId(v: String?): DBCharge? { _scheduledFailureId = v; return this }

    public fun setScheduledFailure(f: DBScheduledFailure): DBCharge? = setScheduledFailureId(f.id)
    public fun getScheduledFailure(mapper: DynamoDBMapper): DBScheduledFailure? =
            mapper.load(javaClass<DBScheduledFailure>(), _scheduledFailureId)
}
