#!/bin/bash

source $(dirname $0)/common

if shift && [ $# -ne 0 ]; then
    ports="$*"
else
    ports="80 443 3306 1211"
fi

# According to https://github.com/netflix/SimianArmy/blob/master/src/main/resources/scripts/networkloss.sh:
# Drops 7% of packets, with 25% correlation with previous packet loss
# 7% is high, but it isn't high enough that TCP will fail entirely
for IFACE in $IFACES; do
    $(dirname $0)/../network_condition/start $IFACE "$ports" "loss 7% 25%"
done
