#!/bin/bash

source $(dirname $0)/common
iptables-save > $save_file
if [ $? -ne 0 ]; then
    echo "Failed to save iptables rules to $save_file; bailing out."
    exit 1
fi

client=${SSH_CLIENT%% *}

iptables -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -p tcp --source $client -j ACCEPT
iptables -A INPUT -j DROP

iptables -A OUTPUT -p tcp --sport 22 -j ACCEPT
iptables -A OUTPUT -p tcp --destination $client -j ACCEPT
iptables -A OUTPUT -j DROP