#!/bin/bash

source $(dirname $0)/common
iptables-restore < $save_file
if [ $? -ne 0 ]; then
    echo "Failed to restore iptables rules saved when starting from $save_file, flushing iptables."
    iptables -F
fi

rm -f $save_file
