#!/bin/bash
# Endpoints as found on http://docs.aws.amazon.com/general/latest/gr/rande.html on 2014-07-02

. $(dirname $0)/../helpers.sh
save_iptables drop_s3_traffic

drop_traffic_to \
    s3.amazonaws.com \
    s3-external-1.amazonaws.com \
    s3-us-west-2.amazonaws.com \
    s3-us-west-1.amazonaws.com \
    s3-eu-west-1.amazonaws.com \
    s3-ap-southeast-1.amazonaws.com \
    s3-ap-southeast-2.amazonaws.com \
    s3-ap-northeast-1.amazonaws.com \
    s3-sa-east-1.amazonaws.com
